config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :rules
  resources :shedules
  
  resources :matches do
    collection do
      get "mine"
    end

    resources :scores

  end

  resources :seasons do
    resources :divisions do
      # TODO: add matches and scores as nested routes
      member do
        get "join"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/season.rb
class Season < ApplicationRecord

  has_many :divisions, dependent: :destroy

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all()
  end

  def show
    @season = Season.find(params[:id])
  end

  def new
    @season = Season.new
  end

  def create

    @season = Season.new(season_params)
    # authorize @season

    if @season.save
      redirect_to @season
    else
      render 'new'
    end
  end

  def edit
    @season = Season.find(params[:id])
  end

  def update
    @season = Season.find(params[:id])

    if @season.update(season_params)
      redirect_to @season
    else
      render 'edit'
    end
  end

  def destroy

    # TODO: role based auth

    @season = Season.find(params[:id])
    @season.destroy
    redirect_to seasons_path
  end

  private
  def season_params
    params.require(:season).permit(:name)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with model: @season, local: true do |form| %>

<% if @season.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@season.errors.count, "error") %>
      prohibited this season from being saved:
    </h2>
    <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/seasons/_season.html.erb
<div class="container-fluid">

  <h1 class="text-center">
    Season:
    <%= @season.name %>
  </h1>

  <% if user_signed_in? and (current_user.mod_role? or current_user.admin_role? )%>

    <div class="">
      <%= link_to 'Edit Season', edit_season_path(@season), class: "btn btn-secondary" %>
      <%= link_to 'New division', new_season_division_path(@season), class: "btn btn-secondary" %>
    </div>

  <% end %>

  <%= render @season.divisions %>

  <hr>

</div>

app/views/seasons/edit.html.erb
<div class="container-fluid">

  <h1>New Season</h1>

  <%= render 'form' %>

  <%= link_to 'Back', seasons_path %>

</div>

app/views/seasons/index.html.erb
<h2 class="text-center m-4">Seasons</h2>

<table class="table table-dark">
  <tr>
    <th>Name</th>
    <th>Options</th>
  </tr>

  <% @seasons.each do |season| %>
    <tr>
      <td><%= season.name %></td>

      <td><%= link_to 'Show', season_path(season), class: "btn btn-secondary" %>
        <% if user_signed_in? and current_user.admin_role? || current_user.mod_role? %>
          <%= link_to 'Edit', edit_season_path(season), class: "btn btn-secondary" %>
          <%= link_to 'Destroy', season_path(season), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<% if user_signed_in? and current_user.admin_role? || current_user.mod_role? %>
  <%= link_to 'New season', new_season_path, class: "btn btn-secondary" %>
<% end %>

app/views/seasons/new.html.erb
<div class="container-fluid">

  <h1>New Season</h1>

  <%= render 'form' %>

</div>

app/views/seasons/show.html.erb
<%= render @season %>