config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :rules
  resources :shedules
  
  resources :matches do
    collection do
      get "mine"
    end

    resources :scores

  end

  resources :seasons do
    resources :divisions do
      # TODO: add matches and scores as nested routes
      member do
        get "join"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :match
  belongs_to :user
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  # whole thing is a bit glued togheter and assumes certain behaviour but should work for now

  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @match = Match.find(params[:match_id])
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
    @match = Match.first

  end

  # POST /scores
  # POST /scores.json
  def create

    @match = Match.find(params[:match_id])
    @score = Score.new(score_params)
    @score.match_id = @match.id
    @score.user_id = helpers.current_user.id

    @oponent_score = Score.new
    @oponent_score.match_id = @match.id
    @oponent_score.user_id = @match.users.where.not(id: helpers.current_user.id).first.id
    # invert the loses and wins
    @oponent_score.wins = @score.loses
    @oponent_score.loses =  @score.wins

    if not @score.save! or not @oponent_score.save!
      render 'new'
      return
    end

    redirect_to mine_matches_path()
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:wins, :loses)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with model: [ @match, @match.scores.build], local: true do |form| %>
<% if score.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(score.errors.count, "error") %>
      prohibited this score from being saved:</h2>

    <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label "My Wins" %><br>
  <%= form.number_field(:wins, step: 1) %>
</p>

<p>
  <%= form.label "My Loses" %><br>
  <%= form.number_field(:loses, step: 1) %>
</p>

<div class="actions">
  <%= form.submit(class: "btn btn-secondary")%>
</div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_match_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<br>

<%= link_to 'Back', match_scores_path %>

app/views/scores/show.html.erb
<%= link_to 'Edit', edit_score_path(@score) %>
|
<%= link_to 'Back', scores_path %>