config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :rules
  resources :shedules
  
  resources :matches do
    collection do
      get "mine"
    end

    resources :scores

  end

  resources :seasons do
    resources :divisions do
      # TODO: add matches and scores as nested routes
      member do
        get "join"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cultleague</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand d-none d-sm-block" href="/">Cultris League</a>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">

          <li id="nav-season" class="nav-item">
            <%= link_to 'Seasons', seasons_path, class: "nav-link" %>
          </li>

          <li id="nav-season" class="nav-item">
            <%= link_to 'My matches', mine_matches_path, class: "nav-link" %>
          </li>

          <li id="nav-recent" class="nav-item">
            <%= link_to 'Matches', matches_path, class: "nav-link" %>
          </li>

          <li id="nav-recent" class="nav-item">
            <%= link_to 'Information and Rules', rules_path, class: "nav-link" %>
          </li>

          <li id="nav-recent" class="nav-item">
            <%= link_to 'Schedule', mine_matches_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="https://discord.gg/qYu8RZ4">Discord</a>
          </li>

          <% if user_signed_in? %>
            <li id="nav-recent" class="nav-item">
              <%= link_to link_to current_user.username, edit_user_registration_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link", method: :delete %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

      </nav>

      <div class="">
        <% if alert %>
          <div class="alert alert-warning text-center" role="alert">
            <%= alert %>
          </div>
        <% end %>

        <% if notice %>
          <div class="alert alert-info text-center" role="alert">
            <%= notice %>
          </div>
        <% end %>
      </div>

      <%= yield %>

      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    </body>
  </html>